### ISSUE TITLE
meet error py4j.Py4JException: Method reset_mdp([]) does not exist

### ISSUE THREAD

**Issue by kirlaw** [phate09/SafeDRL#1]
when i try to run `runnables/symbolic/dqn/domain_analysis_sym.py`
That error occurred：
```
Resetting the StateStorage
Loading complete
Building the tree
Resetting the tree
Finished building the tree
Iteration 0
Traceback (most recent call last):
  File "runnables/symbolic/dqn/domain_analysis_sym.py", line 46, in <module>
    allow_assign_actions=True)
  File "/usr/local/SafeDRL-master/symbolic/unroll_methods.py", line 599, in probability_iteration
    storage.recreate_prism(horizon * 2)
  File "/usr/local/SafeDRL-master/prism/state_storage.py", line 102, in recreate_prism
    mdp = gateway.entry_point.reset_mdp()
  File "/root/miniconda3/envs/safedrl/lib/python3.7/site-packages/py4j/java_gateway.py", line 1310, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/root/miniconda3/envs/safedrl/lib/python3.7/site-packages/py4j/protocol.py", line 332, in get_return_value
    format(target_id, ".", name, value))
py4j.protocol.Py4JError: An error occurred while calling t.reset_mdp. Trace:
py4j.Py4JException: Method reset_mdp([]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```
why come to that
Is it due to spark version?

**Comment by phate09** [comment]
Hello kirlaw, thanks for your interest in my work. I'll look into the problem and let you know in the next few days

**Comment by kirlaw** [comment]
> Hello kirlaw, thanks for your interest in my work. I'll look into the problem and let you know in the next few days

Hi, can you tell me what version of java and py4j do you use

**Comment by kirlaw** [comment]
> Hello kirlaw, thanks for your interest in my work. I'll look into the problem and let you know in the next few days

Hello, can you tell me how to run prism with gradle, i think i run it in a wrong way. Orz

**Comment by phate09** [comment]
Sure, in the Readme file I mention a fork of the PRISM repository. you just need to clone it, access the top folder and type "gradle run" in the terminal. this requires to have installed gradle (https://gradle.org/install/)

Regarding the issue, the codebase changed so much and parts of the code are now broken. I'll try to fix it asap but it is going to take longer. If you need it urgently send me an email and we can try to arrange an online meeting.

**Comment by kirlaw** [comment]
Thank you for your propose, I have sent an email to your gmail :)
